name: "\U0001F50D Spike"
description: Create an issue for an investigation or evaluation.
labels: ["triage/needed", "time/needed"]
type: spike
projects: ["roclub/9", "roclub/21"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief overview of the task and its objectives. What is the addressed problem?
      placeholder: Insert description here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context information needed to adequately work on this issue. Feel free to link to diagrams, internal or external references.
      placeholder: Insert context here...
    validations:
      required: false

  - type: textarea
    id: desired-solution
    attributes:
      label: Desired Solution
      description: What requirements or problems shall the outcome of this exploration fulfill?
      placeholder: Insert desired solution here...
    validations:
      required: true
